# Generated by Django 3.1.3 on 2020-11-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Phone_no',
            field=models.PositiveIntegerField(),
        ),
    ]
